const nodemailer = require('nodemailer');

let testTransporter = null;

async function getTransporter() {
    const rawUser = process.env.SMTP_USER || process.env.GMAIL_USER || process.env.EMAIL_USER || '';
    const rawPass = process.env.SMTP_PASS || process.env.GMAIL_PASS || process.env.EMAIL_PASS || '';
    const smtpUser = rawUser.trim();
    const smtpPass = rawPass.replace(/\s+/g, '');

    // If Gmail / SMTP environment variables exist, use them to deliver real emails
    if (smtpUser && smtpPass) {
        return nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: smtpUser,
                pass: smtpPass,
            },
        });
    }

    // Fallback to Ethereal Test SMTP for local development/testing
    if (!testTransporter) {
        try {
            const testAccount = await nodemailer.createTestAccount();
            testTransporter = nodemailer.createTransport({
                host: 'smtp.ethereal.email',
                port: 587,
                secure: false,
                auth: {
                    user: testAccount.user,
                    pass: testAccount.pass,
                },
            });
            console.log('📧 Created Ethereal Test Mailer Account:', testAccount.user);
        } catch (err) {
            console.warn('Could not create test mail account:', err.message);
            return null;
        }
    }
    return testTransporter;
}

function resolveDisplayName(name, email) {
    if (name && typeof name === 'string' && name.trim()) {
        return name.trim();
    }
    if (email && typeof email === 'string' && email.includes('@')) {
        const prefix = email.split('@')[0].replace(/[._-]+/g, ' ').trim();
        if (prefix) {
            return prefix.charAt(0).toUpperCase() + prefix.slice(1);
        }
    }
    return 'Valued Member';
}

/**
 * Sends an automated welcome email to the newly registered user (Farmer or Student).
 * Triggers ONLY at registration time.
 *
 * @param {Object} params
 * @param {string} params.toEmail - User's Gmail / email address
 * @param {string} [params.name] - User's full name
 * @param {'farmer'|'student'} [params.role='farmer'] - Role registered
 */
async function sendWelcomeEmail({ toEmail, name, role = 'farmer' }) {
    try {
        if (!toEmail) {
            console.warn('⚠️ sendWelcomeEmail skipped: No recipient email provided.');
            return { success: false, error: 'No recipient email provided' };
        }

        const transporter = await getTransporter();
        if (!transporter) {
            console.warn('⚠️ sendWelcomeEmail skipped: No mail transporter available.');
            return { success: false, error: 'No mail transporter configured' };
        }

        const isStudent = String(role).toLowerCase() === 'student';
        const displayName = resolveDisplayName(name, toEmail);
        const smtpSender = process.env.SMTP_USER || process.env.GMAIL_USER || 'no-reply@agriiproject.app';

        let subject = '';
        let plainText = '';
        let htmlContent = '';

        if (!isStudent) {
            // 🌱 FARMER WELCOME TEMPLATE
            subject = 'Welcome to AgriiProject | Your Smart Agriculture Journey Begins';

            plainText = `Dear ${displayName},

Thank you for creating your account with AgriiProject.

We’re pleased to welcome you to our agricultural technology platform, where technology, data, and agricultural knowledge come together to support smarter farming decisions.

As a Farmer, your AgriiProject experience is designed to help you access useful resources and intelligent tools related to:

Crop selection and recommendations
Weather and forecast information
Crop disease identification
Fertilizer and farming guidance
Agricultural learning resources
AI-powered assistance for farming-related queries

We encourage you to explore your dashboard and make use of the tools available to you.

Your journey toward smarter and more informed farming starts here.

Thank you for being a part of AgriiProject.

Warm regards,
Team AgriiProject
Technology for Smarter Agriculture

This is an automated message generated by AgriiProject. If you did not create this account, please contact our support team.

This message was generated with the assistance of AI to provide personalized communication.`;

            htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${subject}</title>
</head>
<body style="margin: 0; padding: 24px 12px; background-color: #F4F1E8; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #212529; line-height: 1.6;">
  <div style="max-width: 580px; margin: 0 auto; background: #ffffff; border-radius: 14px; overflow: hidden; border: 1px solid #E2DCC8; box-shadow: 0 4px 20px rgba(0,0,0,0.05);">
    
    <!-- Top Brand Header -->
    <div style="background: #1E3A2B; padding: 28px 32px; text-align: left; border-bottom: 3px solid #D9A441;">
      <div style="display: inline-block; background: rgba(217, 164, 65, 0.2); border: 1px solid #D9A441; border-radius: 20px; padding: 4px 12px; margin-bottom: 8px;">
        <span style="color: #F4F1E6; font-size: 12px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase;">🌱 Farmer Portal</span>
      </div>
      <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.01em;">AgriiProject</h1>
      <p style="color: #E2E8F0; margin: 4px 0 0 0; font-size: 13.5px; opacity: 0.9;">Technology for Smarter Agriculture</p>
    </div>

    <!-- Email Body -->
    <div style="padding: 32px;">
      <p style="font-size: 16px; color: #1E3A2B; font-weight: 600; margin-top: 0;">Dear ${displayName},</p>
      
      <p style="font-size: 15px; color: #334155; margin: 16px 0;">
        Thank you for creating your account with <strong>AgriiProject</strong>.
      </p>
      
      <p style="font-size: 15px; color: #334155; margin: 16px 0;">
        We’re pleased to welcome you to our agricultural technology platform, where technology, data, and agricultural knowledge come together to support smarter farming decisions.
      </p>

      <div style="background: #FAF8F2; border: 1px solid #EAE5D9; border-radius: 10px; padding: 20px 22px; margin: 24px 0;">
        <p style="font-size: 14.5px; font-weight: 600; color: #1E3A2B; margin: 0 0 12px 0;">
          As a Farmer, your AgriiProject experience is designed to help you access useful resources and intelligent tools related to:
        </p>
        <ul style="margin: 0; padding-left: 20px; color: #475569; font-size: 14px; line-height: 1.8;">
          <li>Crop selection and recommendations</li>
          <li>Weather and forecast information</li>
          <li>Crop disease identification</li>
          <li>Fertilizer and farming guidance</li>
          <li>Agricultural learning resources</li>
          <li>AI-powered assistance for farming-related queries</li>
        </ul>
      </div>

      <p style="font-size: 15px; color: #334155; margin: 16px 0;">
        We encourage you to explore your dashboard and make use of the tools available to you.
      </p>

      <p style="font-size: 15px; color: #1E3A2B; font-weight: 600; margin: 16px 0;">
        Your journey toward smarter and more informed farming starts here.
      </p>

      <!-- Dashboard Button -->
      <div style="text-align: center; margin: 28px 0;">
        <a href="http://localhost:4000/dashboard.html" style="background: #1E3A2B; color: #ffffff; text-decoration: none; padding: 13px 32px; border-radius: 8px; font-weight: 600; font-size: 14.5px; display: inline-block; letter-spacing: 0.01em;">
          🌾 Open Farmer Dashboard
        </a>
      </div>

      <p style="font-size: 15px; color: #334155; margin: 24px 0 6px 0;">
        Thank you for being a part of AgriiProject.
      </p>

      <div style="margin-top: 20px; padding-top: 18px; border-top: 1px solid #E2E8F0;">
        <p style="font-size: 14.5px; color: #334155; margin: 0;">Warm regards,</p>
        <p style="font-size: 15px; font-weight: 700; color: #1E3A2B; margin: 2px 0 0 0;">Team AgriiProject</p>
        <p style="font-size: 13px; color: #64748b; margin: 2px 0 0 0;">Technology for Smarter Agriculture</p>
      </div>
    </div>

    <!-- Footer -->
    <div style="background: #F8FAFC; border-top: 1px solid #E2E8F0; padding: 20px 32px; font-size: 12px; color: #64748B; line-height: 1.5;">
      <p style="margin: 0 0 8px 0;">
        This is an automated message generated by AgriiProject. If you did not create this account, please contact our support team.
      </p>
      <p style="margin: 0; color: #94A3B8; font-style: italic;">
        This message was generated with the assistance of AI to provide personalized communication.
      </p>
    </div>

  </div>
</body>
</html>
            `;
        } else {
            // 🎓 STUDENT WELCOME TEMPLATE
            subject = 'Welcome to AgriiProject | Start Exploring Agriculture & Technology';

            plainText = `Dear ${displayName},

Thank you for creating your account with AgriiProject.

We’re delighted to welcome you to our platform, where agriculture, technology, learning, and innovation come together.

As a Student, AgriiProject provides you with access to resources and tools designed to help you explore the intersection of technology and modern agriculture.

Through your AgriiProject account, you can explore:

Agricultural learning resources
Modern farming technologies
AI applications in agriculture
Crop and plant disease information
Weather and agricultural data
Technology-driven solutions for farming
Opportunities to learn, experiment, and innovate

Take some time to explore your personalized dashboard and discover what AgriiProject has to offer.

Learn. Explore. Innovate. Grow.

We’re happy to have you as a part of the AgriiProject community.

Warm regards,
Team AgriiProject
Technology for Smarter Agriculture

This is an automated message generated by AgriiProject. If you did not create this account, please contact our support team.

This message was generated with the assistance of AI to provide personalized communication.`;

            htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${subject}</title>
</head>
<body style="margin: 0; padding: 24px 12px; background-color: #F4F1E8; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #212529; line-height: 1.6;">
  <div style="max-width: 580px; margin: 0 auto; background: #ffffff; border-radius: 14px; overflow: hidden; border: 1px solid #E2DCC8; box-shadow: 0 4px 20px rgba(0,0,0,0.05);">
    
    <!-- Top Brand Header -->
    <div style="background: #173322; padding: 28px 32px; text-align: left; border-bottom: 3px solid #D9A441;">
      <div style="display: inline-block; background: rgba(217, 164, 65, 0.2); border: 1px solid #D9A441; border-radius: 20px; padding: 4px 12px; margin-bottom: 8px;">
        <span style="color: #F4F1E6; font-size: 12px; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase;">🎓 Student Portal</span>
      </div>
      <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.01em;">AgriiProject</h1>
      <p style="color: #E2E8F0; margin: 4px 0 0 0; font-size: 13.5px; opacity: 0.9;">Start Exploring Agriculture & Technology</p>
    </div>

    <!-- Email Body -->
    <div style="padding: 32px;">
      <p style="font-size: 16px; color: #173322; font-weight: 600; margin-top: 0;">Dear ${displayName},</p>
      
      <p style="font-size: 15px; color: #334155; margin: 16px 0;">
        Thank you for creating your account with <strong>AgriiProject</strong>.
      </p>
      
      <p style="font-size: 15px; color: #334155; margin: 16px 0;">
        We’re delighted to welcome you to our platform, where agriculture, technology, learning, and innovation come together.
      </p>

      <p style="font-size: 15px; color: #334155; margin: 16px 0;">
        As a Student, AgriiProject provides you with access to resources and tools designed to help you explore the intersection of technology and modern agriculture.
      </p>

      <div style="background: #FAF8F2; border: 1px solid #EAE5D9; border-radius: 10px; padding: 20px 22px; margin: 24px 0;">
        <p style="font-size: 14.5px; font-weight: 600; color: #173322; margin: 0 0 12px 0;">
          Through your AgriiProject account, you can explore:
        </p>
        <ul style="margin: 0; padding-left: 20px; color: #475569; font-size: 14px; line-height: 1.8;">
          <li>Agricultural learning resources</li>
          <li>Modern farming technologies</li>
          <li>AI applications in agriculture</li>
          <li>Crop and plant disease information</li>
          <li>Weather and agricultural data</li>
          <li>Technology-driven solutions for farming</li>
          <li>Opportunities to learn, experiment, and innovate</li>
        </ul>
      </div>

      <p style="font-size: 15px; color: #334155; margin: 16px 0;">
        Take some time to explore your personalized dashboard and discover what AgriiProject has to offer.
      </p>

      <div style="background: #EEF6F0; border-left: 4px solid #2B6E44; padding: 12px 16px; margin: 20px 0; border-radius: 4px;">
        <p style="font-size: 15px; font-weight: 700; color: #1E3A2B; margin: 0; letter-spacing: 0.02em;">
          Learn. Explore. Innovate. Grow.
        </p>
      </div>

      <!-- Dashboard Button -->
      <div style="text-align: center; margin: 28px 0;">
        <a href="http://localhost:4000/student-dashboard.html" style="background: #173322; color: #ffffff; text-decoration: none; padding: 13px 32px; border-radius: 8px; font-weight: 600; font-size: 14.5px; display: inline-block; letter-spacing: 0.01em;">
          📚 Open Student Dashboard
        </a>
      </div>

      <p style="font-size: 15px; color: #334155; margin: 24px 0 6px 0;">
        We’re happy to have you as a part of the AgriiProject community.
      </p>

      <div style="margin-top: 20px; padding-top: 18px; border-top: 1px solid #E2E8F0;">
        <p style="font-size: 14.5px; color: #334155; margin: 0;">Warm regards,</p>
        <p style="font-size: 15px; font-weight: 700; color: #173322; margin: 2px 0 0 0;">Team AgriiProject</p>
        <p style="font-size: 13px; color: #64748b; margin: 2px 0 0 0;">Technology for Smarter Agriculture</p>
      </div>
    </div>

    <!-- Footer -->
    <div style="background: #F8FAFC; border-top: 1px solid #E2E8F0; padding: 20px 32px; font-size: 12px; color: #64748B; line-height: 1.5;">
      <p style="margin: 0 0 8px 0;">
        This is an automated message generated by AgriiProject. If you did not create this account, please contact our support team.
      </p>
      <p style="margin: 0; color: #94A3B8; font-style: italic;">
        This message was generated with the assistance of AI to provide personalized communication.
      </p>
    </div>

  </div>
</body>
</html>
            `;
        }

        const mailOptions = {
            from: `"AgriiProject" <${smtpSender}>`,
            to: toEmail,
            subject: subject,
            text: plainText,
            html: htmlContent,
        };

        const info = await transporter.sendMail(mailOptions);
        const previewUrl = nodemailer.getTestMessageUrl(info);

        console.log(`✉️ [AgriiProject] Welcome Email sent to ${toEmail} (${role.toUpperCase()})`);
        if (previewUrl) {
            console.log(`🔗 [AgriiProject] Test Email Preview URL: ${previewUrl}`);
        }

        return {
            success: true,
            previewUrl: previewUrl || null,
            messageId: info.messageId,
            role: role
        };
    } catch (err) {
        console.error('❌ FAILED TO SEND WELCOME EMAIL:', err.message);
        return { success: false, error: err.message };
    }
}

async function sendResetEmail(toEmail, resetLinkOrCode) {
    try {
        const transporter = await getTransporter();
        if (!transporter) return { success: false, error: 'No mail transporter configured' };

        const smtpSender = process.env.SMTP_USER || process.env.GMAIL_USER || 'no-reply@agriiproject.app';

        const mailOptions = {
            from: `"AgriiProject Security" <${smtpSender}>`,
            to: toEmail,
            subject: '🔒 Reset Your AgriiProject Password',
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 540px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background: #FAF8F5;">
                    <div style="text-align: center; margin-bottom: 20px;">
                        <h2 style="color: #1E3A2B; margin: 0;">🌱 AgriiProject</h2>
                        <p style="color: #64748b; font-size: 14px; margin-top: 4px;">Password Reset Request</p>
                    </div>
                    <div style="background: #ffffff; padding: 24px; border-radius: 8px; border: 1px solid #cbd5e1;">
                        <p style="font-size: 15px; color: #1e293b;">Hello,</p>
                        <p style="font-size: 14.5px; color: #334155; line-height: 1.5;">We received a request to reset the password for your AgriiProject account (<strong>${toEmail}</strong>).</p>
                        <div style="text-align: center; margin: 24px 0;">
                            <a href="${resetLinkOrCode}" style="background: #1E3A2B; color: #ffffff; text-decoration: none; padding: 12px 28px; font-weight: bold; border-radius: 8px; display: inline-block;">Reset Password Now</a>
                        </div>
                        <p style="font-size: 13px; color: #64748b;">If the button above does not work, copy and paste this link into your browser:<br/><a href="${resetLinkOrCode}" style="color: #2A4D69;">${resetLinkOrCode}</a></p>
                    </div>
                    <p style="font-size: 12px; color: #94a3b8; text-align: center; margin-top: 20px;">If you did not request a password reset, you can safely ignore this email.</p>
                </div>
            `
        };

        const info = await transporter.sendMail(mailOptions);
        const previewUrl = nodemailer.getTestMessageUrl(info);
        if (previewUrl) {
            console.log('✉️ PASSWORD RESET PREVIEW URL:', previewUrl);
        }
        return { success: true, previewUrl, messageId: info.messageId };
    } catch (err) {
        console.error('FAILED TO SEND EMAIL:', err);
        return { success: false, error: err.message };
    }
}

module.exports = {
    sendWelcomeEmail,
    sendResetEmail,
    getTransporter
};
